src/apps/client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    path('admin/', views.admin_view, name='admin'),
    path('search/', views.search_view, name='search'),
    path('delete/<int:contact_id>', views.delete_view, name='delete'),
    path('export/', views.export_view, name='export'),
]

src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('apps.core.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('client/', include('apps.client.urls')),
    # path('', lambda request: redirect('accounts:login')),
]

# DEBUG モードのときだけ debug_toolbar を使う
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/client/models.py
from django.db import models

# Create your models here.

src/apps/core/models.py
from django.db import models


class Contact(models.Model):
    GENDER_CHOICES = [
        (1, '男性'),
        (2, '女性'),
        (3, '未回答'),
    ]
    CATEGORY_CHOICES = [
        (1, '商品のお届けについて'),
        (2, '商品の交換について'),
        (3, '商品トラブル'),
        (4, 'ショップへのお問い合わせ'),
        (5, 'その他'),
    ]
    first_name = models.CharField(
        verbose_name='名',
        max_length=100,
        null=False,
        blank=False
    )
    last_name = models.CharField(
        verbose_name='姓',
        max_length=100,
        null=False,
        blank=False
    )
    gender = models.PositiveSmallIntegerField(
        verbose_name='性別',
        choices=GENDER_CHOICES,
        default=3
    )
    email = models.EmailField(
        verbose_name='メールアドレス',
        null=False,
        blank=False
    )
    tell = models.CharField(
        verbose_name='電話番号',
        max_length=20,
        null=False,
        blank=False
    )
    address = models.CharField(
        verbose_name='住所',
        max_length=255,
        null=False,
        blank=False
    )
    building = models.CharField(
        verbose_name='建物名',
        max_length=255,
        null=True,
        blank=True
    )
    category = models.PositiveSmallIntegerField(
        verbose_name='お問い合わせの種類',
        choices=CATEGORY_CHOICES
    )
    detail = models.TextField(
        verbose_name='お問い合わせ内容',
        null=False,
        blank=False
    )
    created_at = models.DateTimeField(verbose_name='お問い合わせ日', auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/apps/client/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.http import require_http_methods, require_safe
from .utils import get_filtered_contacts # 検索機能
from apps.core.models import Contact

import csv, logging


@login_required
@require_safe
def admin_view(request):
    contacts = Contact.objects.all().order_by('-created_at')
    paginator = Paginator(contacts, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'contacts': page_obj,
        'gender_choices': Contact.GENDER_CHOICES, # セレクトボックス用
        'category_choices': Contact.CATEGORY_CHOICES, # セレクトボックス用
    }

    return render(request, 'client/admin.html', context)


@login_required
@require_http_methods(["GET"])
def search_view(request):
    contacts = get_filtered_contacts(request.GET)

    paginator = Paginator(contacts, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    params = request.GET.copy()
    if 'page' in params:
        del params['page']
    get_params = "&" + params.urlencode() if params else ""
    context = {
        'contacts': page_obj,
        'get_params': get_params,
        'gender_choices': Contact.GENDER_CHOICES, # セレクトボックス用
        'category_choices': Contact.CATEGORY_CHOICES, # セレクトボックス用
    }

    return render(request, 'client/admin.html', context)


@login_required
@require_http_methods(["POST"])
def delete_view(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)
    contact.delete()

    return redirect('client:admin')


logger = logging.getLogger(__name__) # エクスポートのログを保存

@login_required
@require_http_methods(["GET"])
def export_view(request):
    contacts = get_filtered_contacts(request.GET)

    # csvヘッダーを持つHttpResponseオブジェクトの作成
    response = HttpResponse(
        content_type="text/csv",
        headers={ "Content-Disposition": 'attachment; filename="inquiry_list.csv"' },
    )

    # csvライターを初期化
    writer = csv.writer(response)

    # ヘッダー行の追加
    writer.writerow([
        "姓",
        "名",
        "性別",
        "メールアドレス",
        "電話番号",
        "住所",
        "建物名",
        "お問い合わせの種類",
        "お問い合わせ内容",
        "お問い合わせ日"
    ])

    # データ行の追加
    for contact in contacts:
        writer.writerow([
            contact.last_name,
            contact.first_name,
            contact.get_gender_display(),
            contact.email,
            contact.tell,
            contact.address,
            contact.building or '',
            contact.get_category_display(),
            contact.detail,
            contact.created_at.strftime('%Y-%m-%d %H:%M'),
        ])

    logger.info(f"{request.user} exported {contacts.count()} contact(s) at {timezone.now()}")

    return response

src/apps/client/templates/client/admin.html
{% extends "layouts/admin_layout.html" %}
{% load static %}

{% block extraheader %}
    <link rel="stylesheet" href="{% static 'client/css/admin.css' %}">
{% endblock %}

{% block content %}
    <div class="admin">
        <h2 class="admin-title">Admin</h2>
        <div class="admin-container">
            <div class="search-wrapper">
                <form class="search-form" action="{% url 'client:search' %}" method="GET">
                    <div class="keyword-wrapper">
                        <input class="search-keyword search-input" type="text" name="keyword"
                            value="{{ request.GET.keyword }}" placeholder="名前やメールアドレスを入力してください">
                    </div>
                    <div class="gender-wrapper">
                        <select class="search-gender search-input" name="gender">
                            <option value="" hidden>性別</option>
                            {% for value, label in gender_choices %}
                                <option value="{{ value }}"
                                    {% if request.GET.gender|stringformat:"s" == value|stringformat:"s" %}selected{% endif %}>
                                    {{ label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="category-wrapper">
                        <select class="search-category search-input" name="category">
                            <option value="" hidden>お問い合わせの種類</option>
                            {% for value, label in category_choices %}
                                <option value="{{ value }}"
                                    {% if request.GET.category|stringformat:"s" == value|stringformat:"s" %}selected{% endif %}>
                                    {{ label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="created_at-wrapper">
                        <input class="search-created_at search-input" type="date" name="created_at"
                            value="{{ request.GET.created_at }}">
                    </div>
                    <button class="search-button" type="submit">検索</button>
                    <a class="search-reset" href="{% url 'client:admin' %}">リセット</a>
                </form>
            </div>
            <div class="option">
                <div class="export"> {# エクスポート機能 #}
                    <form class="export-form" action="{% url 'client:export' %}" method="GET">
                        <input type="hidden" name="keyword" value="{{ request.GET.keyword }}">
                        <input type="hidden" name="gender" value="{{ request.GET.gender }}">
                        <input type="hidden" name="category" value="{{ request.GET.category }}">
                        <input type="hidden" name="created_at" value="{{ request.GET.created_at }}">
                        <button class="export-button" type="submit">エクスポート</button>
                    </form>
                </div>
                <div class="pagination"> {# ページネーション機能 #}
                    <ul class="pagination-list">
                        {% if contacts.has_previous %}
                            <li><a href="?page={{ contacts.previous_page_number }}{{ get_params }}">&lt;</a></li>
                        {% else %}
                            <li class="disabled"><span>&lt;</span></li>
                        {% endif %}

                        {% for num in contacts.paginator.page_range %}
                            {% if contacts.number == num %}
                                <li class="active"><span>{{ num }}</span></li>
                            {% elif num >= contacts.number|add:'-2' and num <= contacts.number|add:'4' %}
                                <li><a href="?page={{ num }}{{ get_params }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if contacts.has_next %}
                            <li><a href="?page={{ contacts.next_page_number }}{{ get_params }}">&gt;</a></li>
                        {% else %}
                            <li class="disabled"><span>&gt;</span></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <table class="list-table">
                <thead class="list-header">
                    <tr class="list-title">
                        <th class="list-title__name">お名前</th>
                        <th class="list-title__name">性別</th>
                        <th class="list-title__name">メールアドレス</th>
                        <th class="list-title__name">お問い合わせの種類</th>
                        <th class="list-title__name">&nbsp;</th>
                    </tr>
                </thead>
                <tbody class="list-content">
                    {% for contact in contacts %}
                        <tr class="list-item">
                            <td class="item-value">{{ contact.last_name }}&nbsp;{{ contact.first_name }}</td>
                            <td class="item-value">{{ contact.get_gender_display }}</td>
                            <td class="item-value">{{ contact.email }}</td>
                            <td class="item-value">{{ contact.get_category_display }}</td>
                            <td class="item-value">
                                <button class="modal-button__show" popovertarget="modal-{{ contact.id }}"
                                    popovertargetaction="show">
                                    詳細
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% for contact in contacts %}
                <div class="modal-container" id="modal-{{ contact.id }}" popover="auto">
                    <div class="modal-inner">
                        <button class="modal-button__close" popovertarget="modal-{{ contact.id }}" popovertargetaction="hidden">
                            <img src="{% static 'client/img/close_button_icon.png' %}" alt="クローズボタン">
                        </button>
                        <table class="modal-table">
                            <tbody class="modal-content">
                                <tr class="modal-item">
                                    <th class="modal-item__name">お名前</th>
                                    <td class="modal-item__value">{{ contact.last_name }}&nbsp;{{ contact.first_name }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">性別</th>
                                    <td class="modal-item__value">{{ contact.get_gender_display }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">メールアドレス</th>
                                    <td class="modal-item__value">{{ contact.email }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">電話番号</th>
                                    <td class="modal-item__value">{{ contact.tell }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">住所</th>
                                    <td class="modal-item__value">{{ contact.address }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">建物名</th>
                                    <td class="modal-item__value">{{ contact.building|default:'' }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">お問い合わせの種類</th>
                                    <td class="modal-item__value">{{ contact.get_category_display }}</td>
                                </tr>
                                <tr class="modal-item">
                                    <th class="modal-item__name">お問い合わせ内容</th>
                                    <td class="modal-item__value">{{ contact.detail }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="delete-container">
                            <button class="delete-button__show" popovertarget="delete-{{ contact.id }}"
                                popovertargetaction="show">
                                削除
                            </button>
                            <div class="delete-content" id="delete-{{ contact.id }}" popover="auto">
                                <div class="delete-inner">
                                    <div class="delete-item">
                                        <form class="delete-form"
                                            action="{% url 'client:delete' contact.id %}" method="POST">
                                            {% csrf_token %}
                                            <p class="delete-message">本当に削除しますか？</p>
                                            <button class="delete-button" type="submit">削除する</button>
                                        </form>
                                    </div>
                                    <button class="delete-button__cancel" popovertarget="delete-{{ contact.id }}"
                                        popovertargetaction="hidden">
                                        キャンセル
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}